import type { NextConfig } from "next";

const pipelineRuntimeFiles = [
  "./scripts/**/*",
  "./package.json",
  "./node_modules/@google/genai/**/*",
  "./node_modules/@protobufjs/aspromise/**/*",
  "./node_modules/@protobufjs/base64/**/*",
  "./node_modules/@protobufjs/codegen/**/*",
  "./node_modules/@protobufjs/eventemitter/**/*",
  "./node_modules/@protobufjs/fetch/**/*",
  "./node_modules/@protobufjs/float/**/*",
  "./node_modules/@protobufjs/path/**/*",
  "./node_modules/@protobufjs/pool/**/*",
  "./node_modules/@protobufjs/utf8/**/*",
  "./node_modules/@types/node/**/*",
  "./node_modules/@types/retry/**/*",
  "./node_modules/@vercel/blob/**/*",
  "./node_modules/@vercel/cli-config/**/*",
  "./node_modules/@vercel/cli-exec/**/*",
  "./node_modules/@vercel/oidc/**/*",
  "./node_modules/agent-base/**/*",
  "./node_modules/async-retry/**/*",
  "./node_modules/base64-js/**/*",
  "./node_modules/bignumber.js/**/*",
  "./node_modules/buffer-equal-constant-time/**/*",
  "./node_modules/cross-spawn/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/debug/**/*",
  "./node_modules/dotenv/**/*",
  "./node_modules/ecdsa-sig-formatter/**/*",
  "./node_modules/execa/**/*",
  "./node_modules/extend/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/formdata-polyfill/**/*",
  "./node_modules/gaxios/**/*",
  "./node_modules/gcp-metadata/**/*",
  "./node_modules/get-stream/**/*",
  "./node_modules/google-auth-library/**/*",
  "./node_modules/google-logging-utils/**/*",
  "./node_modules/https-proxy-agent/**/*",
  "./node_modules/human-signals/**/*",
  "./node_modules/is-buffer/**/*",
  "./node_modules/is-node-process/**/*",
  "./node_modules/is-stream/**/*",
  "./node_modules/isexe/**/*",
  "./node_modules/jose/**/*",
  "./node_modules/json-bigint/**/*",
  "./node_modules/jsonrepair/**/*",
  "./node_modules/jwa/**/*",
  "./node_modules/jws/**/*",
  "./node_modules/long/**/*",
  "./node_modules/merge-stream/**/*",
  "./node_modules/mimic-fn/**/*",
  "./node_modules/ms/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/npm-run-path/**/*",
  "./node_modules/onetime/**/*",
  "./node_modules/os-paths/**/*",
  "./node_modules/p-retry/**/*",
  "./node_modules/path-key/**/*",
  "./node_modules/protobufjs/**/*",
  "./node_modules/retry/**/*",
  "./node_modules/safe-buffer/**/*",
  "./node_modules/shebang-command/**/*",
  "./node_modules/shebang-regex/**/*",
  "./node_modules/signal-exit/**/*",
  "./node_modules/strip-final-newline/**/*",
  "./node_modules/throttleit/**/*",
  "./node_modules/undici/**/*",
  "./node_modules/undici-types/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/which/**/*",
  "./node_modules/ws/**/*",
  "./node_modules/xdg-app-paths/**/*",
  "./node_modules/xdg-portable/**/*",
  "./node_modules/zod/**/*"
];

const nextConfig: NextConfig = {
  outputFileTracingIncludes: {
    "/api/run-pipeline-step": pipelineRuntimeFiles,
    "/api/leads": pipelineRuntimeFiles,
    "/api/leads-csv": pipelineRuntimeFiles,
    "/api/reveal-leads-next": pipelineRuntimeFiles,
    "/api/run-signal-scan": pipelineRuntimeFiles,
    "/api/enrich-next-batch": pipelineRuntimeFiles,
    "/api/prefetch-next-batch": pipelineRuntimeFiles,
    "/api/enrichment-status": pipelineRuntimeFiles
  }
};

export default nextConfig;
